version: '3.7'
services:
  pong:
    container_name: pong-application
    build:
      context: pong
      dockerfile: Dockerfile
    network_mode: "host"
  ping:
    depends_on:
      - pong
    container_name: ping-application
    build:
      context: ping
      dockerfile: Dockerfile
    network_mode: "host"
